[package]
name = "olord-hosting"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-multipart = "0.7.2"
actix-web = "4.9.0"
futures-util = "0.3.30"
uuid = { version = "1.10.0", features = ["v4"] }
